Bootstrap: docker
From: python:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-nanoplot
    COPYRIGHT Copyright © 2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.42.0

%post
    apt update
    pip install NanoPlot --upgrade

%runscript
    /usr/local/bin/NanoPlot "$@"
